### Bow and Tf-idf machine learning algorithms or techniques
In general Machine Computers do not understands the direct sentences , so the sentences must convert into numerical values .
So we use the techniques called Bag of words and term Frequeny - invert document frequency 
Each has differrent approaches 
1)Bag of Words
It uses the vocabulary(unique words)
and then calculates the value for the words , It gives equal priority to every word

2)Term Frequency and Invert Document Frequency
It gives high priority to the important words
It often measures how many times a word appeared in the sentece
and applies a logarithmic Formula

### Word2Vec 
    -> It is also a nlp technique to convert words to vectors 
    -> It was published by the google 
    -> The model trains over a 3 billion words
    -> The words are converted in to vectors , intially the model assigns random values to the words , each word represented as the 
    -> 300 dimensional vector and lastly averages the vector values into a single vector of 300 dimension

### Basic Workflow of a machine learning algorithm
    ->Preprocessing and Cleaning
    ->Train and Test split
    ->BOW and TF-IDF (Sentences --> Vectors)
    ->ML Models To train the data


### Re Module
re stands for Regular Expressions is a Module in python is used in searching ,matching , replacing , and manipulating the text patterns
-> To keep only alphabets in the dataset 
        -> use text='i love! python, programming language'
        -> clean_text=re.sub(r'[^a-zA-Z ]','',text)
    -> re.sub(pattern,replacement,string)

### Split function returns a list of words from a text
    text=text.split() -> default method to separate the text based on the space
    text=text.split(',') -> separate based on the comma

### Difference betweeen the fit_transform and Transform
    fit-> learns patterns from the data like a relationship 
    transform-> applies that pattern to the data
So we use the fit_transform on the train data to learn a relationship
and apply the transform on the test data on unseen data like applying a same relationship on the unseen data

### Cosine similarity 
        -> It is a measure used to determine how similar two vectors are
        -> It tells is the two values related or not
        -> it ranges from -1 0 1

In [126]:
import pandas as pd
df=pd.read_csv("SMSSpamCollection",sep='\t',names=['label','message'])

In [127]:
df.head()

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [128]:
df

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


### Make a Small dataset from the big dataset
df.sample --> used random samples
df.head(150) --> used first 150 samples

In [129]:
df_small=df.sample(n=150,random_state=42)
df_small=df_small.reset_index(drop=True)

In [130]:
df_small.head()

,label,message
0,ham,Squeeeeeze!! This is christmas hug.. If u lik ...
1,ham,And also I've sorta blown him off a couple tim...
2,ham,Mmm thats better now i got a roast down me! i’...
3,ham,Mm have some kanji dont eat anything heavy ok
4,ham,So there's a ring that comes with the guys cos...


In [131]:
df_small

,label,message
0,ham,Squeeeeeze!! This is christmas hug.. If u lik ...
1,ham,And also I've sorta blown him off a couple tim...
2,ham,Mmm thats better now i got a roast down me! i’...
3,ham,Mm have some kanji dont eat anything heavy ok
4,ham,So there's a ring that comes with the guys cos...
...,...,...
145,ham,You might want to pull out more just in case a...
146,spam,PRIVATE! Your 2004 Account Statement for 07849...
147,ham,:-( sad puppy noise
148,ham,4 oclock at mine. Just to bash out a flat plan.


In [132]:
df_small['label'].value_counts()

label
ham     133
spam     17
Name: count, dtype: int64

In [133]:
df_small.shape

(150, 2)

In [134]:
df_small['message']

0      Squeeeeeze!! This is christmas hug.. If u lik ...
1      And also I've sorta blown him off a couple tim...
2      Mmm thats better now i got a roast down me! i’...
3          Mm have some kanji dont eat anything heavy ok
4      So there's a ring that comes with the guys cos...
                             ...                        
145    You might want to pull out more just in case a...
146    PRIVATE! Your 2004 Account Statement for 07849...
147                                  :-( sad puppy noise
148      4 oclock at mine. Just to bash out a flat plan.
149    We not watching movie already. Xy wants 2 shop...
Name: message, Length: 150, dtype: object

In [135]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
lemmatizer=WordNetLemmatizer()
import re

In [136]:
corpus=[]
for i in range (0,len(df_small)):
    review=re.sub('[^a-zA-Z]',' ',df_small['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [137]:
corpus

['squeeeeeze christmas hug u lik frndshp den hug back u get u r cute u r luvd u r lucky none people hate u',
 'also sorta blown couple time recently id rather text blue looking weed',
 'mmm thats better got roast b better drink good indian',
 'mm kanji dont eat anything heavy ok',
 'ring come guy costume gift future yowifes hint hint',
 'sary need tim bollox hurt lot tol',
 'love decision feeling could decide love life would much simpler less magical',
 'supervisor find one lor thk student havent ask yet tell u aft ask',
 'dear good morning',
 'chennai velachery',
 'lol grr mom taking forever prescription pharmacy like minute away ugh',
 'valentine huh proof fb page ugh glad really watch rupaul show tool',
 'wif buying tix lar',
 'er hello thing quite go plan limping slowly home followed aa exhaust hanging',
 'free ringtone text first poly text get true tone help st free tone x pw e nd txt stop',
 'sir waiting call',
 'crazy ar married like gd looking guy frens like say korean leona fa

In [138]:
### Extract Output feature
y=pd.get_dummies(df_small['label'])

In [139]:
y

,ham,spam
0,True,False
1,True,False
2,True,False
3,True,False
4,True,False
...,...,...
145,True,False
146,False,True
147,True,False
148,True,False


In [140]:
y=y.iloc[:,0].values

In [141]:
y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,

In [142]:
type(corpus),type(y)

(list, numpy.ndarray)

In [143]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.2)

In [144]:
len(X_train),len(y_train)

(120, 120)

In [145]:
len(X_test),len(y_test)

(30, 30)

In [146]:
### For small dataset we don't use the max_feature parameter
#Bag of words
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(ngram_range=(1,2))

In [147]:
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [148]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(120, 1598))

In [149]:
cv.vocabulary_

{'maybe': 844,
 'fat': 427,
 'finger': 452,
 'press': 1064,
 'button': 161,
 'know': 723,
 'maybe fat': 845,
 'fat finger': 428,
 'finger press': 453,
 'press button': 1065,
 'button know': 162,
 'aiyar': 30,
 'poor': 1051,
 'thing': 1359,
 'give': 509,
 'support': 1309,
 'jia': 695,
 'think': 1364,
 'aiyar poor': 31,
 'poor thing': 1052,
 'thing give': 1360,
 'give support': 512,
 'support jia': 1310,
 'jia think': 696,
 'even': 398,
 'friend': 479,
 'priest': 1068,
 'call': 165,
 'even friend': 399,
 'friend priest': 480,
 'priest call': 1069,
 'gudnite': 576,
 'tc': 1332,
 'practice': 1058,
 'going': 533,
 'gudnite tc': 577,
 'tc practice': 1333,
 'practice going': 1059,
 'pls': 1043,
 'send': 1201,
 'mail': 819,
 'relative': 1136,
 'coming': 245,
 'deliver': 324,
 'cost': 264,
 'risk': 1160,
 'benefit': 108,
 'anything': 48,
 'else': 376,
 'thanks': 1351,
 'pls pls': 1044,
 'pls send': 1045,
 'send mail': 1202,
 'mail know': 820,
 'know relative': 727,
 'relative coming': 1137,
 'c

## Machine Learning Model Multinomial naive bayes

In [150]:
from sklearn.naive_bayes import MultinomialNB

In [151]:
spam_model_bow=MultinomialNB().fit(X_train,y_train)

In [152]:
y_pred_bow=spam_model_bow.predict(X_test)

In [153]:
from sklearn.metrics import accuracy_score,classification_report

print(accuracy_score(y_test,y_pred_bow))
print(classification_report(y_test,y_pred_bow))

0.9333333333333333
              precision    recall  f1-score   support

       False       0.75      0.75      0.75         4
        True       0.96      0.96      0.96        26

    accuracy                           0.93        30
   macro avg       0.86      0.86      0.86        30
weighted avg       0.93      0.93      0.93        30



## Tf-idf

In [155]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.2)

In [157]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv=TfidfVectorizer(ngram_range=(1,2))

X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [158]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(120, 1789))

In [159]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(30, 1789))

In [160]:
cv.vocabulary_

{'maybe': 844,
 'fat': 427,
 'finger': 452,
 'press': 1064,
 'button': 161,
 'know': 723,
 'maybe fat': 845,
 'fat finger': 428,
 'finger press': 453,
 'press button': 1065,
 'button know': 162,
 'aiyar': 30,
 'poor': 1051,
 'thing': 1359,
 'give': 509,
 'support': 1309,
 'jia': 695,
 'think': 1364,
 'aiyar poor': 31,
 'poor thing': 1052,
 'thing give': 1360,
 'give support': 512,
 'support jia': 1310,
 'jia think': 696,
 'even': 398,
 'friend': 479,
 'priest': 1068,
 'call': 165,
 'even friend': 399,
 'friend priest': 480,
 'priest call': 1069,
 'gudnite': 576,
 'tc': 1332,
 'practice': 1058,
 'going': 533,
 'gudnite tc': 577,
 'tc practice': 1333,
 'practice going': 1059,
 'pls': 1043,
 'send': 1201,
 'mail': 819,
 'relative': 1136,
 'coming': 245,
 'deliver': 324,
 'cost': 264,
 'risk': 1160,
 'benefit': 108,
 'anything': 48,
 'else': 376,
 'thanks': 1351,
 'pls pls': 1044,
 'pls send': 1045,
 'send mail': 1202,
 'mail know': 820,
 'know relative': 727,
 'relative coming': 1137,
 'c

In [165]:
from sklearn.naive_bayes import MultinomialNB

spam_tfidf_model=MultinomialNB().fit(X_train,y_train)

In [166]:
y_pred_tfidf=spam_tfidf_model.predict(X_test)

In [167]:
print(accuracy_score(y_test,y_pred_tfidf))

1.0


In [168]:
print(classification_report(y_test,y_pred_tfidf))

              precision    recall  f1-score   support

        True       1.00      1.00      1.00        30

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

