In [1]:
import random

print(random.random())  #Prints a float number

0.43961614195753895


In [2]:
print(random.randint(1,10))

6


In [3]:
print(random.randrange(1,20,3))

16


In [4]:
a=['apple','banana','cucumber']
print(random.choice(a))
print(random.choices(a,k=10))

cucumber
['apple', 'banana', 'apple', 'cucumber', 'cucumber', 'apple', 'banana', 'apple', 'cucumber', 'banana']


In [5]:
b=[1,3,4,2,5,3,6]

print(random.sample(b,3))

[3, 5, 6]


In [6]:
c=[1,2,3,4,5,6]         #shuffles the positions
random.shuffle(c)
print(c)

[3, 5, 2, 6, 1, 4]


In [7]:
print(random.uniform(10,20))        

19.935834853412317


In [8]:
#randn is a numpy random module which selects a random value of gausian distribution 
#Gausian distribution means values that are near 0

import numpy as np

print(np.random.randn())

0.21090996762734907


In [9]:
print(np.random.randn(5))

[-1.2112878   1.34486857 -1.21535827 -1.02072993  0.57658212]


In [10]:
print(np.random.randn(2,3))     #Creates 2*3 matrix

[[ 1.58284715 -1.78787338 -1.40469023]
 [-1.50127585  0.97177365 -0.4369789 ]]


In [11]:
x=6*np.random.randn(100,1)-3
print(x)

[[  3.93677255]
 [ -2.67222129]
 [  1.06329493]
 [ -5.58147402]
 [-22.59124778]
 [ -3.21391599]
 [ -5.74182567]
 [ -4.19264591]
 [  3.20071014]
 [-12.37883269]
 [ -5.23334116]
 [ -2.36273618]
 [  1.02874302]
 [ -7.40580334]
 [ -7.02510113]
 [ -4.35427158]
 [-16.53612256]
 [ -0.44945456]
 [  5.78519696]
 [ -3.78271469]
 [-12.65241631]
 [ -3.26086628]
 [ -7.37830984]
 [ -2.08082299]
 [  5.25977047]
 [ -8.06351735]
 [ -2.94197774]
 [ -3.34126701]
 [ -6.71913559]
 [ -1.90395161]
 [ -3.80832222]
 [ -5.81006079]
 [ -5.81339856]
 [  0.43732132]
 [  1.64742346]
 [  6.0988415 ]
 [-13.61151185]
 [-14.16945504]
 [  2.56592578]
 [ -2.53157977]
 [ -1.59230946]
 [ -4.73440208]
 [-14.77298048]
 [ -0.18782767]
 [ -8.9606205 ]
 [-10.32178514]
 [ -5.14259537]
 [-18.69323416]
 [  6.84510483]
 [ -2.00799075]
 [ -4.46850673]
 [ -3.68159887]
 [  0.9594963 ]
 [ -8.36287741]
 [  6.14972695]
 [ -6.1205863 ]
 [ -1.391273  ]
 [ -1.13974946]
 [ 11.29138973]
 [  0.34554051]
 [-11.70133483]
 [-10.08835789]
 [ -0.38

In [12]:
import numpy as np
x=np.linspace(-3, 3, 10)        #It generates 10 equally spaced numbers between -3 and 3
print(x)

[-3.         -2.33333333 -1.66666667 -1.         -0.33333333  0.33333333
  1.          1.66666667  2.33333333  3.        ]


In [13]:
x=np.arange(-1,5,2)         #It generates numbers between -1 to 5 with step size 2
print(x)

[-1  1  3]


### np.where is a function which returns the list of indecies where the certain condition is met

It is a useful function

In [ ]:
arr=np.array([10,20,30,40,50])
result=np.where(arr > 20)
print(result)               #returns the indecies

(array([2, 3, 4]),)


In [16]:
arr=np.array([10,20,30,40,50])
result=np.where(arr > 20 , "High","low")
print(result)

['low' 'low' 'High' 'High' 'High']


In [17]:
arr=np.array([10,20,30,40,50])
result=np.where(arr > 20 ,1,0)
print(result)

[0 0 1 1 1]
